name: Example
on:
  pull_request:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Modules
        shell: bash
        run: npm ci
      - name: Run Tests
        shell: bash
        run: npm run example