name: Example
on:
  pull_request:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Get Action
        uses: actions/checkout@v3
        with:
          repository: Dawid-Oskwarek/broken-link-checker-action
          ref: main
          path: ./
      - name: Check for Broken Links
        uses: ./
        with:
          urlsToCheck: 'https://www.google.com'
