name: Test
on:
  pull_request:
  workflow_dispatch:
jobs:
  exampleJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Modules
        shell: bash
        run: npm ci
      - name: Install Act
        shell: bash
        run: brew install act
      - name: Run Tests
        shell: bash
        run: npm run example