name: Test-Cases
on:
  workflow_dispatch:
jobs:
  exampleJob:
    runs-on: ubuntu-latest
    steps:
      - name: Get Action
        uses: actions/checkout@v3
        with:
          repository: Dawid-Oskwarek/broken-link-checker-action
          ref: main
          token: ${{ secrets.TOKEN }}
          path: ./
      - name: Check for Broken Links
        uses: ./
        with:
          urlsToCheck: 'https://www.google.com'
